// Copied from ibayanihub-mobile/ibayanihub/screens/data/vicariates.js
export const vicariateData = [
    { label: 'VICARIATE OF SANTA CLARA DE MONTEFALCO', value: null, isHeader: true  },
    { label: 'MARY, COMFORTER OF THE AFFLICTED', value: 'MARY, COMFORTER OF THE AFFLICTED' },
    { label: 'OUR LADY OF FATIMA', value: 'OUR LADY OF FATIMA' },
    { label: 'OUR LADY OF SORROWS', value: 'OUR LADY OF SORROWS' },
    { label: 'OUR LADY OF THE MOST BLESSED SACRAMENT', value: 'OUR LADY OF THE MOST BLESSED SACRAMENT' },
    { label: 'SAN ISIDRO LABRADOR', value: 'SAN ISIDRO LABRADOR' },
    { label: 'SAN JUAN NEPOMUCENO', value: 'SAN JUAN NEPOMUCENO' },
    { label: 'SAN RAFAEL', value: 'SAN RAFAEL' },
    { label: 'SAN ROQUE ( PASAY )', value: 'SAN ROQUE ( PASAY )' },
    { label: 'STA. CLARA DE MONTEFALCO', value: 'STA. CLARA DE MONTEFALCO' },
    { label: 'OUR LADY OF THE AIRWAYS', value: 'OUR LADY OF THE AIRWAYS' },
    { label: 'VICARIATE OF OUR LADY OF GUADALUPE', value: null, isHeader: true  },
    { label: 'NATIONAL SHRINE OF OUR LADY OF GUADALUPE', value: 'NATIONAL SHRINE OF OUR LADY OF GUADALUPE' },
    { label: 'MATER DOLOROSA', value: 'MATER DOLOROSA' },
    { label: 'MARY, MIROR OF JUSTICE', value: 'MARY, MIROR OF JUSTICE' },
    { label: 'ST. JOHN MARY VIANNEY', value: 'ST. JOHN MARY VIANNEY' },
    { label: 'ST. JOHN OF THE CROSS', value: 'ST. JOHN OF THE CROSS' },
    { label: 'STA. TERESITA', value: 'STA. TERESITA' },
    { label: 'VICARIATE OF SAINTS PETER AND PAUL', value: null, isHeader: true  },
    { label: 'HOLY CROSS', value: 'HOLY CROSS' },
    { label: 'NUESTRA SRA. DE GRACIA', value: 'NUESTRA SRA. DE GRACIA' },
    { label: 'ST. JOHN BOSCO, (MAKATI)', value: 'ST. JOHN BOSCO, (MAKATI)' },
    { label: 'STS. PETER & PAUL', value: 'STS. PETER & PAUL' },
    { label: 'NATIONAL SHRINE OF THE SACRED HEART OF JESUS', value: 'NATIONAL SHRINE OF THE SACRED HEART OF JESUS' },
    { label: 'OUR LADY OF LA PAZ', value: 'OUR LADY OF LA PAZ' },
    { label: 'VICARIATE OF SAINT JOSEPH THE WORKER', value: null, isHeader: true  },
    { label: 'HOLY FAMILY', value: 'HOLY FAMILY' },
    { label: 'OUR LADY OF FATIMA', value: 'OUR LADY OF FATIMA' },
    { label: 'ST. JOSEPH THE WORKER', value: 'ST. JOSEPH THE WORKER' },
    { label: 'SAN ILDEFONSO', value: 'SAN ILDEFONSO' },
    { label: 'VICARIATE OF SAN FELIPE NERI', value: null, isHeader: true  },
    { label: 'SAN FELIPE NERI', value: 'SAN FELIPE NERI' },
    { label: 'SAN ROQUE ( MANDALUYONG )', value: 'SAN ROQUE ( MANDALUYONG )' },
    { label: 'ST. DOMINIC SAVIO', value: 'ST. DOMINIC SAVIO' },
    { label: 'SACRED HEART OF JESUS', value: 'SACRED HEART OF JESUS' },
    { label: 'PARISH OF OUR LADY OF ABANDONED', value: 'PARISH OF OUR LADY OF ABANDONED' },
    { label: 'OUR LADY OF FATIMA', value: 'OUR LADY OF FATIMA' },
    { label: 'VICARIATE OF SAINT JOHN THE BAPTIST', value: null, isHeader: true  },
    { label: 'MARY THE QUEEN', value: 'MARY THE QUEEN' },
    { label: 'ST. JOHN THE BAPTIST', value: 'ST. JOHN THE BAPTIST' },
    { label: 'SANTUARIO DE SAN JOSE', value: 'SANTUARIO DE SAN JOSE' },
    { label: 'SANTUARIO DE STO. CRISTO', value: 'SANTUARIO DE STO. CRISTO' },
    { label: 'VICARIATE OF HOLY FAMILY', value: null, isHeader: true  },
    // ... (truncated for brevity, copy all entries as needed)
];
